# Generated by Django 4.1.5 on 2023-04-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('physics_mark', models.IntegerField()),
                ('chemistry_mark', models.IntegerField()),
                ('maths_mark', models.IntegerField()),
                ('computer_science_mark', models.IntegerField()),
            ],
        ),
    ]
